### PR TITLE
Makes the ouija board responsive

### PR DESCRIPTION
**Pull request by SaptakS**
- Make the cursor change on hover as well
- Make the board into 3 rows for mobile version
- Made the fonts a bit bold

I haven't made the background board responsive since it is not yet finalized. This just handles the character positioning for mobile responsive. I personally am finding the board as a background a bit problematic with all rotation and stuff. Probably can move the board background to `.ouija::before` instead of `.ouija-letters::before` since it is rotated.

### CODE REVIEW

**Comment by SaptakS** [comment]
I also added the cursor on hover, because I felt that made sense based on what the issue stated, but I am worried about the UX a bit since finding another link when the cursor is on one link is difficult.

**Comment by ahmadalfy** [comment]
> Probably can move the board background to `.ouija::before` instead of `.ouija-letters::before` since it is rotated.

Yeah it was a little bit problematic and I had to counter rotate it. Let's see what's the final decision for the board because the image we use at the moment requires commercial license.

> I am worried about the UX a bit since finding another link when the cursor is on one link is difficult

This is why I added to focus only

**Comment by SaptakS** [comment]
> This is why I added to focus only

Yeah I thought of that too. Let's see what @matuzo says. I am okay with removing it from hover.

**Comment by matuzo** [comment]
@SaptakS @ahmadalfy Adding `pointer-events: none;` to the pseudo element makes it slightly better. For a no-js version that's more than good enough, but I think we should enhance this with JS and make the cursor move with the mouse. This will allow us to animate the movement and make it smoother and more precise. I'm not asking you to do that, you've done already a lot, but if you want to, give it a shot. :)

**Pull request merged**
